spring:
  application:
    name: SecurePay
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${{ secrets.POSTGRE_URL }}
    username: ${{ secrets.DB_USERNAME }} 
    password: ${{ secrets.POSTGRE_PASSWORD }}
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /index.html
    groups-order: asc
  cache:
    disabled: true
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-login-endpoint: true #로그인 시 swagger에 표시하려고 하는 표현

logging:
  file:
    name: logs/devcamp.log
  logback:
    rolling policy:
      max-file-size: 50MB
      max-history: 7
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log

jwt:
  secret:
    key: ${{ secrets.JWT_KEY }}
